#!/usr/bin/env python3
"""Transcribe SQLGlot's per-dialect Generator.TYPE_MAPPING into Rust.

This is the "port SQLGlot's dicts as data" tool: instead of rediscovering
type-rendering rules from suite diffs, we read them straight from SQLGlot's
generator classes and emit `src/dialects/rules.rs` type tables.

Usage:
    SQLGLOT_PYTHON_PATH=/path/to/sqlglot python3 parity/scripts/transcribe_sqlglot_types.py

It prints Rust `match` arms for `map_type(target, upper_name)`, one helper fn
per target dialect. The mapping is keyed by the canonical DataType.Type name
(which, for the exotic types this matters for — NCHAR, MEDIUMTEXT, DATETIME2,
ROWVERSION, ... — equals the source spelling sqlgrok carries as Unknown).
"""
import sys
import os

sys.path.insert(0, os.environ.get("SQLGLOT_PYTHON_PATH", "/Users/russellromney/Documents/Github/sqlglot"))
import sqlglot  # noqa: E402
from sqlglot.dialects.dialect import Dialect  # noqa: E402

# sqlgrok's builtin Dialect enum variants we generate tables for.
DIALECTS = {
    "Sqlite": "sqlite",
    "Postgres": "postgres",
    "Mysql": "mysql",
    "Tsql": "tsql",
    "DuckDb": "duckdb",
    "Oracle": "oracle",
    "Snowflake": "snowflake",
    "BigQuery": "bigquery",
}


def type_mapping(sqlglot_name: str) -> dict[str, str]:
    gen = Dialect.get_or_raise(sqlglot_name).generator()
    out = {}
    for k, v in gen.TYPE_MAPPING.items():
        # v is a string spelling; k is exp.DataType.Type
        out[k.name] = v
    return dict(sorted(out.items()))


def emit():
    print("// AUTO-GENERATED by parity/scripts/transcribe_sqlglot_types.py")
    print("// from SQLGlot's per-dialect Generator.TYPE_MAPPING. Do not hand-edit;")
    print("// re-run the script to refresh. Keyed by canonical type name (uppercase).")
    print()
    for rust_variant, sqlglot_name in DIALECTS.items():
        tm = type_mapping(sqlglot_name)
        helper = f"map_type_{sqlglot_name.lower()}"
        print(f"fn {helper}(upper_name: &str) -> Option<&'static str> {{")
        print("    let mapped = match upper_name {")
        # group identical targets onto one arm
        groups: dict[str, list[str]] = {}
        for canon, spelling in tm.items():
            groups.setdefault(spelling, []).append(canon)
        for spelling, canons in sorted(groups.items()):
            keys = " | ".join(f'"{c}"' for c in sorted(canons))
            print(f'        {keys} => "{spelling}",')
        print("        _ => return None,")
        print("    };")
        print("    Some(mapped)")
        print("}")
        print()


if __name__ == "__main__":
    emit()
