#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include "sqlgrok.h"

typedef struct {
    const char *id;
    const char *sql;
    const char *read;
    const char *write;
} bench_case_t;

static const bench_case_t MYSQL_SQLITE[] = {
    {"mysql-group-concat-order-separator", "SELECT GROUP_CONCAT(v ORDER BY v SEPARATOR '|') FROM gc", "mysql", "sqlite"},
    {"mysql-json-extract-key", "SELECT JSON_EXTRACT(data, '$.k') FROM events WHERE id = 1", "mysql", "sqlite"},
    {"mysql-limit-offset-comma", "SELECT a, b FROM t WHERE a > 10 ORDER BY b DESC LIMIT 5, 10", "mysql", "sqlite"},
    {"mysql-date-format", "SELECT DATE_FORMAT(created_at, '%Y-%m-%d') FROM users", "mysql", "sqlite"},
    {"mysql-if-cast-div", "SELECT IF(a > 0, CAST(a AS SIGNED INTEGER), 7 DIV 2), x / y FROM metrics", "mysql", "sqlite"},
    {"mysql-insert-ignore", "INSERT IGNORE INTO users (id, email) VALUES (1, 'a@example.com')", "mysql", "sqlite"},
    {"mysql-on-duplicate-key", "INSERT INTO users (id, email) VALUES (1, 'a@example.com') ON DUPLICATE KEY UPDATE email = VALUES(email)", "mysql", "sqlite"},
    {"mysql-computed-column", "CREATE TABLE users (id INT PRIMARY KEY, email VARCHAR(255), email_lc VARCHAR(255) AS (LOWER(email)) STORED)", "mysql", "sqlite"},
};

static const bench_case_t POSTGRES_SQLITE[] = {
    {"postgres-distinct-on", "SELECT DISTINCT ON (account_id) account_id, created_at FROM events ORDER BY account_id, created_at DESC", "postgres", "sqlite"},
    {"postgres-json-path-text", "SELECT payload #>> '{customer,0,name}' FROM events WHERE payload ->> 'kind' = 'signup'", "postgres", "sqlite"},
    {"postgres-extract-date-trunc", "SELECT EXTRACT(YEAR FROM CAST(created_at AS DATE)), DATE_TRUNC('month', created_at) FROM events", "postgres", "sqlite"},
    {"postgres-rollup", "SELECT region, product, SUM(revenue) FROM sales GROUP BY ROLLUP(region, product)", "postgres", "sqlite"},
    {"postgres-window-nulls", "SELECT user_id, ROW_NUMBER() OVER (PARTITION BY account_id ORDER BY created_at) FROM events", "postgres", "sqlite"},
    {"postgres-offset-only", "SELECT x FROM y OFFSET 10", "postgres", "sqlite"},
    {"postgres-identity-column", "CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TIMESTAMP DEFAULT now())", "postgres", "sqlite"},
    {"postgres-string-agg", "SELECT string_agg(name, ',') FROM users GROUP BY account_id", "postgres", "sqlite"},
};

static const bench_case_t SQLITE_SQLITE[] = {
    {"sqlite-simple-select", "SELECT a, b FROM t WHERE a > 10 ORDER BY b DESC LIMIT 10 OFFSET 5", "sqlite", "sqlite"},
    {"sqlite-json-type", "SELECT JSON_TYPE(data, '$.k') FROM events", "sqlite", "sqlite"},
    {"sqlite-create-table", "CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT NOT NULL UNIQUE, created_at TEXT DEFAULT CURRENT_TIMESTAMP)", "sqlite", "sqlite"},
    {"sqlite-insert-or-ignore", "INSERT OR IGNORE INTO users (id, email) VALUES (1, 'a@example.com')", "sqlite", "sqlite"},
    {"sqlite-window", "SELECT user_id, ROW_NUMBER() OVER (PARTITION BY account_id ORDER BY created_at) FROM events", "sqlite", "sqlite"},
    {"sqlite-cte", "WITH a AS (SELECT 1 AS x), b AS (SELECT 2 AS y) SELECT a.x + b.y FROM a, b", "sqlite", "sqlite"},
    {"sqlite-count-distinct", "SELECT COUNT(DISTINCT name) FROM users GROUP BY account_id", "sqlite", "sqlite"},
    {"sqlite-alter-table", "ALTER TABLE users ADD COLUMN created_at TEXT DEFAULT CURRENT_TIMESTAMP", "sqlite", "sqlite"},
};

typedef struct {
    long long elapsed_ns;
    double ns_per_op;
    unsigned int checksum;
} sample_t;

static long long now_ns(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long long)ts.tv_sec * 1000000000LL + ts.tv_nsec;
}

static int cmp_double(const void *left, const void *right) {
    const double a = *(const double *)left;
    const double b = *(const double *)right;
    return (a > b) - (a < b);
}

static double percentile(const double *values, int count, double q) {
    double *copy = malloc(sizeof(double) * (size_t)count);
    if (!copy) return 0.0;
    memcpy(copy, values, sizeof(double) * (size_t)count);
    qsort(copy, (size_t)count, sizeof(double), cmp_double);
    int index = (int)(q * count + 0.999999999) - 1;
    if (index < 0) index = 0;
    if (index >= count) index = count - 1;
    double value = copy[index];
    free(copy);
    return value;
}

static void select_workload(const char *name, const bench_case_t **cases, int *count) {
    if (strcmp(name, "mysql") == 0 || strcmp(name, "mysql-sqlite") == 0) {
        *cases = MYSQL_SQLITE;
        *count = (int)(sizeof(MYSQL_SQLITE) / sizeof(MYSQL_SQLITE[0]));
    } else if (strcmp(name, "sqlite") == 0 || strcmp(name, "sqlite-sqlite") == 0) {
        *cases = SQLITE_SQLITE;
        *count = (int)(sizeof(SQLITE_SQLITE) / sizeof(SQLITE_SQLITE[0]));
    } else {
        *cases = POSTGRES_SQLITE;
        *count = (int)(sizeof(POSTGRES_SQLITE) / sizeof(POSTGRES_SQLITE[0]));
    }
}

static unsigned int call_allocated(const bench_case_t *c) {
    char *out = sqlgrok_transpile(c->sql, c->read, c->write);
    if (!out) {
        fprintf(stderr, "transpile failed for %s\n", c->id);
        exit(2);
    }
    unsigned int len = (unsigned int)strlen(out);
    sqlgrok_free(out);
    return len;
}

static unsigned int call_into(const bench_case_t *c) {
    char buffer[4096];
    const long required = sqlgrok_transpile_into(c->sql, c->read, c->write, buffer, sizeof(buffer));
    if (required < 0 || (size_t)required >= sizeof(buffer)) {
        fprintf(stderr, "transpile_into failed for %s (required=%ld)\n", c->id, required);
        exit(2);
    }
    return (unsigned int)required;
}

static unsigned int call_version(void) {
    return (unsigned int)strlen(sqlgrok_version());
}

int main(int argc, char **argv) {
    const char *workload = "postgres";
    const char *mode = "allocated";
    int iterations = 1000;
    int warmup = 100;
    int samples_count = 5;

    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--workload") == 0 && i + 1 < argc) workload = argv[++i];
        else if (strcmp(argv[i], "--mode") == 0 && i + 1 < argc) mode = argv[++i];
        else if (strcmp(argv[i], "--iterations") == 0 && i + 1 < argc) iterations = atoi(argv[++i]);
        else if (strcmp(argv[i], "--warmup") == 0 && i + 1 < argc) warmup = atoi(argv[++i]);
        else if (strcmp(argv[i], "--samples") == 0 && i + 1 < argc) samples_count = atoi(argv[++i]);
        else {
            fprintf(stderr, "usage: %s [--workload mysql|postgres|sqlite] [--mode allocated|into|version] [--iterations N] [--warmup N] [--samples N]\n", argv[0]);
            return 2;
        }
    }

    const bench_case_t *cases = NULL;
    int case_count = 0;
    select_workload(workload, &cases, &case_count);
    const int operations = strcmp(mode, "version") == 0 ? iterations : iterations * case_count;
    sample_t *samples = calloc((size_t)samples_count, sizeof(sample_t));
    double *ns_values = calloc((size_t)samples_count, sizeof(double));
    if (!samples || !ns_values) return 2;

    unsigned int checksum = 0;
    for (int i = 0; i < warmup; i++) {
        if (strcmp(mode, "version") == 0) {
            checksum += call_version();
        } else {
            for (int j = 0; j < case_count; j++) {
                checksum += strcmp(mode, "into") == 0 ? call_into(&cases[j]) : call_allocated(&cases[j]);
            }
        }
    }

    for (int sample = 0; sample < samples_count; sample++) {
        checksum = 0;
        const long long started = now_ns();
        for (int i = 0; i < iterations; i++) {
            if (strcmp(mode, "version") == 0) {
                checksum += call_version();
            } else {
                for (int j = 0; j < case_count; j++) {
                    checksum += strcmp(mode, "into") == 0 ? call_into(&cases[j]) : call_allocated(&cases[j]);
                }
            }
        }
        const long long elapsed = now_ns() - started;
        samples[sample].elapsed_ns = elapsed;
        samples[sample].ns_per_op = (double)elapsed / (double)operations;
        samples[sample].checksum = checksum;
        ns_values[sample] = samples[sample].ns_per_op;
    }

    double sum = 0.0;
    double min = ns_values[0];
    double max = ns_values[0];
    for (int i = 0; i < samples_count; i++) {
        if (ns_values[i] < min) min = ns_values[i];
        if (ns_values[i] > max) max = ns_values[i];
        sum += ns_values[i];
    }

    printf("{\"binding\":\"c-abi\",\"workload\":\"%s\",\"mode\":\"%s\",\"cases\":%d,\"iterations\":%d,\"samples\":%d,\"operations\":%d,", workload, mode, case_count, iterations, samples_count, operations);
    printf("\"checksum\":%u,\"min_ns_per_op\":%.3f,\"mean_ns_per_op\":%.3f,\"median_ns_per_op\":%.3f,\"p95_ns_per_op\":%.3f,\"max_ns_per_op\":%.3f,",
           samples[samples_count - 1].checksum, min, sum / samples_count, percentile(ns_values, samples_count, 0.50), percentile(ns_values, samples_count, 0.95), max);
    printf("\"per_sample\":[");
    for (int i = 0; i < samples_count; i++) {
        if (i) printf(",");
        printf("{\"elapsed_ns\":%lld,\"ns_per_op\":%.3f,\"checksum\":%u}", samples[i].elapsed_ns, samples[i].ns_per_op, samples[i].checksum);
    }
    printf("]}\n");

    free(samples);
    free(ns_values);
    return 0;
}
